# Generated by Django 5.1.5 on 2025-02-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('file', models.FileField(upload_to='note_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
